### ISSUE TITLE
Bind shell!

### ISSUE THREAD

**Issue by its0x08** [swisskyrepo/PayloadsAllTheThings#194]
Will there ever be a bind shell cheatsheet?
They are as important as reverse shell, to not say even more ..!
Thanks

**Comment by its0x08** [comment]
Thank you!

**Comment by melardev** [comment]
@its0x08 Hi, I don't know what you are looking for, if its a one liner, then I don't have that, otherwise you may take a look at some projects I made just for fun:
- https://github.com/melardev/C_Win32BindShell
- https://github.com/melardev/.NetCSharpBindShell
- https://github.com/melardev/.NetCoreVBBindShell
- https://github.com/melardev/PythonBindShell
- https://github.com/melardev/JavaBindShell
- https://github.com/melardev/.NetCoreCSharpBindShell
- https://github.com/melardev/KotlinBindShell
- https://github.com/melardev/CppBoostBindShellSync
- https://github.com/melardev/CppWxWidgetsBindShell
- https://github.com/melardev/C_Win32_BindShell_Sync
- https://github.com/melardev/CppQtBindShell

I think these are all bind shells I implemented. Look here for my reverse shell and bind shell implementations:
https://github.com/melardev?tab=repositories&q=shell&type=&language=
The goal was to write code, so they are not one-liners, but they are very simple anyway.
