### ISSUE TITLE
Groovy reverse shell on windows exit immediately

### ISSUE THREAD

**Issue by quinzhi** [swisskyrepo/PayloadsAllTheThings#318]
I run the groovy reverse shell by the nexus repository manager on a Windows Server 2008.
then I run nc -nlvp on a Ubuntu.
the ubuntu shows the "Connection from [xx.xx.xx.xx] port xx [tcp/*] accepted (family 2, sport 60802)" then exited immediately.
Why is that?

**Comment by ProjectZeroDays** [comment]
If your shell env is configured incorrectly and is requesting access to run commands like bash.exe for example it will cause the shell to crash as would powershell invoked from cmd in SSH or bash called remotely using SSH etc from cmd or powershell. That's all I could think of in that scenario minus the remaining obvious bits, your shell may have a bug that doesn't allow it to reset to a previous or default environment when commands or processes are called that cannot be for whatever reasons and instead closes as would be expected I would think in this scenario.

**Comment by quinzhi** [comment]
> e

Thank you for your replay. I try the groovy reverse shell and powercat reverse shell and i got the same result. I think may be the problem is about the firewall and the AV protection

**Comment by quinzhi** [comment]
> If your shell env is configured incorrectly and is requesting access to run commands like bash.exe for example it will cause the shell to crash as would powershell invoked from cmd in SSH or bash called remotely using SSH etc from cmd or powershell. That's all I could think of in that scenario minus the remaining obvious bits, your shell may have a bug that doesn't allow it to reset to a previous or default environment when commands or processes are called that cannot be for whatever reasons and instead closes as would be expected I would think in this scenario.

Thank you for your replay. I try the groovy reverse shell and powercat reverse shell and i got the same result. I think may be the problem is about the firewall and the AV protection

**Comment by ProjectZeroDays** [comment]
You can make windows antivirus call a file from the internet via the command line that will be ignored by default from within the cli. You can write a ducky script or simply python script (I suggest bat or vbs downloader script to install py3 in the background using -j and then download a secondary bat/vbs script that will run your payload that will be downloaded from within windows defender itself via the cli. If you download the raw py file without encoding (a heads-up: without encoding the payload the file will go undetected but with the encoding it will be caught). Your downloader bat/vbs script will run fine with out encoding as well since it won't be doing anything but downloading the raw python code from within defender which will automatically assume the file is safe and will not scan it. Your execution script will run the file downloaded and saved in the tmp folder in defender and deactivate or modify AV so that your reverseshell can run using SSH or whatever type of connection / port youre using. Then, you could even create a provisioned security policy for mobile & desktop devices to connect to your VPN in the cloud using a small free EC2 instance with Ubuntu + OpenVPN for free hosted on AWS and add policy rules to accept incoming and outgoing connections from your host + target devices on various TCP/UDP ports or forward all traffic or only HTTPS traffic to your server where you can then execute a MITM attack vector using Surge on iOS and OSX as the outgoing traffic from target devices send outbound traffic to your global proxy using a certificate and device profile, allowing you to then decrypt traffic and log network activity from all devices within the LAN the target device is on and access their peripherals such as cameras, wifi, and bluetooth devices alike.
