### ISSUE TITLE
Upload insecure files

### ISSUE THREAD

**Issue by SonyKucing** [swisskyrepo/PayloadsAllTheThings#4]
Hy...  i need more explanation about upload insecure files..  when i upload png resize sample on dvwa, how i can i access it ? when i access it in : 
http://localhost/dvwa/hackable/uploads/9375dc00328b26657b48927138ef60ef.png
( on impossible level name of pic will change)
it show png picture ... 
when i add "?0=shell_exec' --data "1='ls'"
it just show detail about that png... 
thanks...

**Comment by swisskyrepo** [comment]
The PNG resize sample is meant to be used with an LFI, you can't just upload it ;)
This payload should be used when a website is resizing your uploaded picture.
In fact the picture will still contain the payload after the resize because of one property of the PNG format, then you can include this picture containing a PHP Code ( system($_GET['c']) for example)

**Comment by SonyKucing** [comment]
so this like insert php code on image with exiftool ? thanks.,,

**Comment by swisskyrepo** [comment]
Yes but if the image is resized with image magik or else you may loose the payload inside the exif data ;)
