### ISSUE TITLE
New Suggestions

### ISSUE THREAD

**Issue by zero77** [swisskyrepo/PayloadsAllTheThings#89]
Cron jobs privilege escalation:
https://0xsp.com/mongoose-linux-exploit-toolkit/ref-001-cron-jobs-privilege-escalation

Red Teaming Toolkit Collection:
https://0xsp.com/offensive/red-teaming-toolkit-collection

Reverse Shell with password protection:
https://0xsp.com/offensive/reverse-shell-with-password

Remote Powershell execution via Lazarus Process unit:
https://0xsp.com/offensive/remote-powershell-execution-via-lazarus-process-unit

**Comment by lucid-star** [comment]
Check cache overflow. I bet there's a leak in the pipe line. Try devotional kits.


_

**Comment by Gorgamite** [comment]
All of these links currently return a 500 server error.

**Comment by zero77** [comment]
https://0xsp.com
The page links have changed, its now down the left hand side.
Also, It looks like there has been content improvements.

**Comment by Gorgamite** [comment]
Can you put the updated specific links for the changes you requested previously?

**Comment by PinkDev1** [comment]
Most of what OP referenced on 0xsp is now outdated, and very poorly documented. Only section that's still relevant is [this](https://0xsp.com/offensive/red-teaming-toolkit-collection). I recommend closing this issue.

**Comment by lawrenceamer** [comment]
@PinkDev1 @zero77 I am the author of 0xsp, due to the recent code update of the site the previous links you can reach via 

https://0xsp.com/offensive/red-ops-techniques/reverse-shell-with-password-protection 
https://0xsp.com/offensive/red-teaming-toolkit-collection
https://0xsp.com/offensive/web-attacks-payloads-collections

some of the mentioned articles were outdated and not fully documented, I will recommend having a look into the newer content as 

https://0xsp.com/security%20dev/0xsp-mongoose-red
